query userQuery($id: Int!){
  user(id: $id) {
    id
    username
    email
    profile {
      firstname
      lastname
      avatar_offset
      avatar_cropped
      avatar
      cover_offset
      cover_cropped
      cover
      bio
    }
  }
}