export const appItems = [
  {
    name: 'Area Chart',
    title: 'Detail of application Area Chart',
    detail: 'Detail of application Area Chart',
    icon: 'area-chart',
    to: '/Area Chart',
    badge: '?',
    options: {
      iconCss: {
        backgroundColor: '#784c84',
        color: '#fff'
      },
      titleCss: {
        color: 'red'
      }
    },
  },
  {
    name: 'android',
    title: 'Android application android',
    detail: 'Detail of application android',
    icon: 'android',
    to: '/android',
    options: {},
  },
  {
    name: 'cloud',
    title: 'Cloud',
    detail: 'Detail of application cloud',
    icon: 'cloud',
    to: '/cloud',
    options: {},
  },
  {
    name: 'windows',
    title: 'Windows',
    detail: 'Detail of application windows',
    icon: 'windows',
    to: '/windows',
    options: {},
  },
  {
    name: 'code',
    title: 'Code',
    detail: 'Detail of application code สวัสดี',
    icon: 'code',
    to: '/code',
    options: {},
  },
  {
    name: 'apple',
    title: 'Apple',
    detail: 'Detail of application apple',
    icon: 'apple',
    to: '/apple',
    options: {},
  },
  {
    name: 'smile',
    title: 'Smile',
    detail: 'Detail of application group work ดีๆๆ',
    icon: 'smile',
    to: '/smile',
  },
  {
    name: 'camera',
    title: 'Camera',
    detail: 'Detail of application camera',
    icon: 'camera',
    to: '/camera',
    options: {},
  },
  {
    name: 'compass',
    title: 'Compass',
    detail: 'Detail of application compass ภาษา',
    icon: 'compass',
    to: '/compass',
    badge: 'En',
    options: {},
  },
  {
    name: 'global',
    title: 'Global',
    detail: 'Detail of application global',
    icon: 'global',
    to: '/global',
    options: {},
  },
  {
    name: 'Area Chart',
    title: 'Detail of application Area Chart',
    detail: 'Detail of application Area Chart',
    icon: 'area-chart',
    to: '/Area Chart',
    badge: '?',
    options: {
      iconCss: {
        backgroundColor: '#784c84',
        color: '#fff'
      },
      titleCss: {
        color: 'red'
      }
    },
  },
  {
    name: 'android',
    title: 'Android',
    detail: 'Detail of application android',
    icon: 'android',
    to: '/android',
    options: {},
  },
  {
    name: 'cloud',
    title: 'Cloud',
    detail: 'Detail of application cloud',
    icon: 'cloud',
    to: '/cloud',
    options: {},
  },
  {
    name: 'windows',
    title: 'Windows',
    detail: 'Detail of application windows',
    icon: 'windows',
    to: '/windows',
    options: {},
  },
  {
    name: 'code',
    title: 'Code',
    detail: 'Detail of application code สวัสดี',
    icon: 'code',
    to: '/code',
    options: {},
  },
  {
    name: 'apple',
    title: 'Apple',
    detail: 'Detail of application apple',
    icon: 'apple',
    to: '/apple',
    options: {},
  },
  {
    name: 'smile',
    title: 'Smile',
    detail: 'Detail of application group work ดีๆๆ',
    icon: 'smile',
    to: '/smile',
  },
  {
    name: 'camera',
    title: 'Camera',
    detail: 'Detail of application camera',
    icon: 'camera',
    to: '/camera',
    options: {},
  },
  {
    name: 'compass',
    title: 'Compass',
    detail: 'Detail of application compass ภาษา',
    icon: 'compass',
    to: '/compass',
    badge: 'En',
    options: {},
  },
  {
    name: 'global',
    title: 'Global',
    detail: 'Detail of application global',
    icon: 'global',
    to: '/global',
    options: {},
  },
  {
    name: 'apple',
    title: 'Apple',
    detail: 'Detail of application apple',
    icon: 'apple',
    to: '/apple',
    options: {},
  },
  {
    name: 'smile',
    title: 'Smile',
    detail: 'Detail of application group work ดีๆๆ',
    icon: 'smile',
    to: '/smile',
  },
  {
    name: 'camera',
    title: 'Camera',
    detail: 'Detail of application camera',
    icon: 'camera',
    to: '/camera',
    options: {},
  },
  {
    name: 'compass',
    title: 'Compass',
    detail: 'Detail of application compass ภาษา',
    icon: 'compass',
    to: '/compass',
    badge: 'En',
    options: {},
  },
  {
    name: 'global',
    title: 'Global',
    detail: 'Detail of application global',
    icon: 'global',
    to: '/global',
    options: {},
  },{
    name: 'Area Chart',
    title: 'Detail of application Area Chart',
    detail: 'Detail of application Area Chart',
    icon: 'area-chart',
    to: '/Area Chart',
    badge: '?',
    options: {
      iconCss: {
        backgroundColor: '#784c84',
        color: '#fff'
      },
      titleCss: {
        color: 'red'
      }
    },
  },
  {
    name: 'android',
    title: 'Android',
    detail: 'Detail of application android',
    icon: 'android',
    to: '/android',
    options: {},
  },
  {
    name: 'cloud',
    title: 'Cloud',
    detail: 'Detail of application cloud',
    icon: 'cloud',
    to: '/cloud',
    options: {},
  },
  {
    name: 'windows',
    title: 'Windows',
    detail: 'Detail of application windows',
    icon: 'windows',
    to: '/windows',
    options: {},
  },
  {
    name: 'code',
    title: 'Code',
    detail: 'Detail of application code สวัสดี',
    icon: 'code',
    to: '/code',
    options: {},
  },
  {
    name: 'apple',
    title: 'Apple',
    detail: 'Detail of application apple',
    icon: 'apple',
    to: '/apple',
    options: {},
  },
]






export const favAppItems = [
  {
    name: 'Area Chart',
    title: 'Detail of application Area Chart',
    detail: 'Detail of application Area Chart',
    icon: 'area-chart',
    to: '/Area Chart',
    badge: '?',
    options: {
      iconCss: {
        backgroundColor: '#784c84',
        color: '#fff'
      },
      titleCss: {
        color: 'red'
      }
    },
  },
  {
    name: 'android',
    title: 'Android application android',
    detail: 'Detail of application android',
    icon: 'android',
    to: '/android',
    options: {},
  },
  {
    name: 'cloud',
    title: 'Cloud',
    detail: 'Detail of application cloud',
    icon: 'cloud',
    to: '/cloud',
    options: {},
  },
  {
    name: 'windows',
    title: 'Windows',
    detail: 'Detail of application windows',
    icon: 'windows',
    to: '/windows',
    options: {},
  },
  {
    name: 'code',
    title: 'Code',
    detail: 'Detail of application code สวัสดี',
    icon: 'code',
    to: '/code',
    options: {},
  },
  {
    name: 'apple',
    title: 'Apple',
    detail: 'Detail of application apple',
    icon: 'apple',
    to: '/apple',
    options: {},
  },
  {
    name: 'smile',
    title: 'Smile',
    detail: 'Detail of application group work ดีๆๆ',
    icon: 'smile',
    to: '/smile',
  },
  {
    name: 'camera',
    title: 'Camera',
    detail: 'Detail of application camera',
    icon: 'camera',
    to: '/camera',
    options: {},
  },
  {
    name: 'compass',
    title: 'Compass',
    detail: 'Detail of application compass เข็มทิศ',
    icon: 'compass',
    to: '/compass',
    badge: 'En',
    options: {},
  },
  {
    name: 'global',
    title: 'Global',
    detail: 'Detail of application global',
    icon: 'global',
    to: '/global',
    options: {},
  },
  {
    name: 'apple',
    title: 'Apple',
    detail: 'Detail of application apple',
    icon: 'apple',
    to: '/apple',
    options: {},
  },
  {
    name: 'smile',
    title: 'Smile',
    detail: 'Detail of application group work ดีๆๆ',
    icon: 'smile',
    to: '/smile',
  },
  {
    name: 'camera',
    title: 'Camera',
    detail: 'Detail of application camera',
    icon: 'camera',
    to: '/camera',
    options: {},
  },
  {
    name: 'compass',
    title: 'Compass',
    detail: 'Detail of application compass ภาษา',
    icon: 'compass',
    to: '/compass',
    badge: 'En',
    options: {},
  },
  {
    name: 'global',
    title: 'Global',
    detail: 'Detail of application global',
    icon: 'global',
    to: '/global',
    options: {},
  },{
    name: 'Area Chart',
    title: 'Detail of application Area Chart',
    detail: 'Detail of application Area Chart',
    icon: 'area-chart',
    to: '/Area Chart',
    badge: '?',
    options: {
      iconCss: {
        backgroundColor: '#784c84',
        color: '#fff'
      },
      titleCss: {
        color: 'red'
      }
    },
  },
  {
    name: 'android',
    title: 'Android',
    detail: 'Detail of application android',
    icon: 'android',
    to: '/android',
    options: {},
  },
  {
    name: 'cloud',
    title: 'Cloud',
    detail: 'Detail of application cloud',
    icon: 'cloud',
    to: '/cloud',
    options: {},
  },
  {
    name: 'windows',
    title: 'Windows',
    detail: 'Detail of application windows',
    icon: 'windows',
    to: '/windows',
    options: {},
  },
  {
    name: 'code',
    title: 'Code',
    detail: 'Detail of application code สวัสดี',
    icon: 'code',
    to: '/code',
    options: {},
  },
  {
    name: 'apple',
    title: 'Apple',
    detail: 'Detail of application apple',
    icon: 'apple',
    to: '/apple',
    options: {},
  },
]